# Generated by Django 2.0.13 on 2019-06-29 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('diag', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Consultas',
                'verbose_name': 'Consulta',
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumExp', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Expedientes',
                'verbose_name': 'Expediente',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePersona', models.CharField(max_length=200)),
                ('dui', models.CharField(max_length=10, unique=True)),
                ('direccion', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=250)),
                ('fechaNac', models.DateField()),
                ('edad', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Personas',
                'verbose_name': 'Persona',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='oftal.Persona')),
                ('remitente', models.CharField(max_length=50)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oftal.Expediente')),
            ],
            options={
                'verbose_name_plural': 'Pacientes',
                'verbose_name': 'Paciente',
            },
            bases=('oftal.persona',),
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='oftal.Persona')),
                ('isss', models.CharField(max_length=12, unique=True)),
                ('afp', models.CharField(max_length=9, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Secretarias',
                'verbose_name': 'Secretaria',
            },
            bases=('oftal.persona',),
        ),
        migrations.AddField(
            model_name='consulta',
            name='expedientePac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oftal.Expediente'),
        ),
        migrations.CreateModel(
            name='Doctora',
            fields=[
                ('secretaria_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='oftal.Secretaria')),
                ('jvpm', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Doctoras',
                'verbose_name': 'Doctora',
            },
            bases=('oftal.secretaria',),
        ),
    ]
