# Generated by Django 2.0.6 on 2019-10-02 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oftal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaventa',
            name='aro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oftal.Lente'),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='lente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oftal.Cristal'),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oftal.Paciente'),
        ),
    ]
