# Generated by Django 2.0.13 on 2019-09-25 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oftal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horaI', models.CharField(max_length=10)),
                ('horaF', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=20)),
                ('paciCita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oftal.Paciente')),
            ],
            options={
                'verbose_name_plural': 'Citas',
                'verbose_name': 'Cita',
            },
        ),
    ]
