# Generated by Django 2.0.13 on 2019-10-02 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oftal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'permissions': (('isDoctora', 'Es Doctora'), ('isSecretaria', 'Es Secretaria')), 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
    ]
