# Generated by Django 2.0.6 on 2019-09-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oftal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cristal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('graduacion', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('precioCompra', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'cristals',
                'verbose_name': 'Cristal',
            },
        ),
    ]
