# Generated by Django 2.0.6 on 2019-09-27 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oftal', '0002_cristal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cristal',
            options={'verbose_name': 'Cristal', 'verbose_name_plural': 'Cristals'},
        ),
    ]
