# Generated by Django 2.0.13 on 2019-07-01 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oftal', '0003_auto_20190629_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.IntegerField(choices=[(1, '--------'), (2, 'Masculino'), (3, 'Femenino')], default=1),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(max_length=9),
        ),
    ]
