# Generated by Django 2.0.6 on 2019-09-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oftal', '0004_auto_20190701_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(max_length=20),
        ),
    ]
